### ISSUE TITLE
[2019-10-24]Today's Plan

### ISSUE THREAD

**Issue by pdji1602003** [pdji1602003/Blog#12]
## Todo 待做事項
1. 今日的工作細項有哪些，請分別列出，並附上粗估工作時間。

- [x] 提出今日工作計畫 - 0.5hr
- [x] 設計我的履歷網站樣式以及功能研究 - 1.5hr
- [x] 理解event物件 - 1hr
- [x] 閱讀[此篇文章](https://ultimatecourses.com/blog/attributes-versus-properties-in-javascript)並寫下心得 - 1hr - 筆記[在此](https://github.com/pdji1602003/Blog/issues/13#issue-511670773)
- [x] 查看自己在StackOverflow上的[提問](https://stackoverflow.com/questions/58526416/how-to-dynamically-fetch-data-nested-in-json-file/)並回覆 - 1hr
- [x] 運動 - 1hr
- [x] 整理環境 - 0.5hr
- [x] Debug my works - 0.5hr

2. 以上工作項目是否都有悉數完成？若無，請說出具體原因，請提出改善作法。

我並沒有完成在StackOverflow上回覆此task，原因是我無法全然理解對方所給出的回覆，特別是以下這個答案：
```
function findNested(obj, key, memo) {
  var i,
      proto = Object.prototype,
      ts = proto.toString,
      hasOwn = proto.hasOwnProperty.bind(obj);

  if ('[object Array]' !== ts.call(memo)) memo = [];

  for (i in obj) {
    if (hasOwn(i)) {
      if (i === key) {
        memo.push(obj[i]);
      } else if ('[object Array]' === ts.call(obj[i]) || '[object Object]' === ts.call(obj[i])) {
        findNested(obj[i], key, memo);
      }
    }
  }

  return memo;
}
```
以上程式碼來源[在此](https://stackoverflow.com/questions/15642494/find-property-by-name-in-a-deep-object/15643382#15643382)。

程式碼中提及JS原型的概念，所以我認為今日除了完成切版的工作之外，也有必要熟悉一下JS中原型的概念。

3. 說一下今天遇到的困難點？以及妳如何解決它？
參考以上第2點。

## Interpretive 反思
1. 我們今天學到了什麼？

2. 今天一個重要的領悟是什麼？

## Other 其他
1. 我今天想跟這世界分享什麼？
這個網站👉：https://www.talesofceylon.com/
